<template>
<div class="row">
	<div class="col-sm-3" v-for="_kink in _kinksList">
		<kink-opt v-bind:kink-name="_kink._name" v-bind:kink-id="_kink._id"></kink-opt>
	</div>
</div>
</template>

<script>
import KinkOpt from './KinkOpt'

export default {
  props: ['_kinksList'],
  ready: function () {
    this._kinksList = [
      {'_id': '001', '_name': 'Ageplay (Young Roles)'},
      {'_id': '002', '_name': 'Anal Sex'},
      {'_id': '003', '_name': 'Anime'},
      {'_id': '004', '_name': 'Bestiality'},
      {'_id': '005', '_name': 'Blackmail'},
      {'_id': '006', '_name': 'Blood'},
      {'_id': '007', '_name': 'Bondage'},
      {'_id': '008', '_name': 'Body Art'},
      {'_id': '009', '_name': 'Boobies'},
      {'_id': '010', '_name': 'Branding'},
      {'_id': '011', '_name': 'Breath-play'},
      {'_id': '012', '_name': 'Bukkake'},
      {'_id': '013', '_name': 'Corsets'},
      {'_id': '014', '_name': 'Cuddling/Snuggling'},
      {'_id': '015', '_name': 'Dungeon-play'},
      {'_id': '016', '_name': 'Electric Play'},
      {'_id': '017', '_name': 'Exhibitionist'},
      {'_id': '018', '_name': 'Facials'},
      {'_id': '019', '_name': 'Fantasy'},
      {'_id': '020', '_name': 'Fear'},
      {'_id': '021', '_name': 'Feet'},
      {'_id': '022', '_name': 'Fire'},
      {'_id': '023', '_name': 'Fisting'},
      {'_id': '024', '_name': 'Food Play'},
      {'_id': '025', '_name': 'Forced-Sex'},
      {'_id': '026', '_name': 'Crossdressing'},
      {'_id': '027', '_name': 'Group Sex'},
      {'_id': '028', '_name': 'Hair'},
      {'_id': '029', '_name': 'Hard Limits'},
      {'_id': '030', '_name': 'Heavy Petting'},
      {'_id': '031', '_name': 'High-Tech'},
      {'_id': '032', '_name': 'Humiliation'},
      {'_id': '033', '_name': 'Ice'},
      {'_id': '034', '_name': 'Incest'},
      {'_id': '035', '_name': 'Insects'},
      {'_id': '036', '_name': 'Kissing'},
      {'_id': '037', '_name': 'Laboratory Scene'},
      {'_id': '038', '_name': 'Lactation'},
      {'_id': '039', '_name': 'Latex/Rubber'},
      {'_id': '040', '_name': 'Leather'},
      {'_id': '041', '_name': 'Machines'},
      {'_id': '042', '_name': 'Magic'},
      {'_id': '043', '_name': 'Masochistic'},
      {'_id': '044', '_name': 'Medical Play'},
      {'_id': '045', '_name': 'Monogamous'},
      {'_id': '046', '_name': 'One-On-One'},
      {'_id': '047', '_name': 'Oral Sex'},
      {'_id': '048', '_name': 'Orgasm Control - Forced'},
      {'_id': '049', '_name': 'Orgasm Control - Prevented'},
      {'_id': '050', '_name': 'Pain'},
      {'_id': '051', '_name': 'Passive'},
      {'_id': '052', '_name': 'Page For Sex'},
      {'_id': '053', '_name': 'Pet Play'},
      {'_id': '054', '_name': 'Petting'},
      {'_id': '055', '_name': 'Consent-Only'},
      {'_id': '056', '_name': 'Training'},
      {'_id': '057', '_name': 'Anal Training'},
      {'_id': '058', '_name': 'Polyamorous'},
      {'_id': '059', '_name': 'Public Sex'},
      {'_id': '060', '_name': 'Oviposition'},
      {'_id': '061', '_name': 'Vore'},
      {'_id': '062', '_name': 'Sleepiness'},
      {'_id': '063', '_name': 'Romantic'},
      {'_id': '064', '_name': 'Sadistic'},
      {'_id': '065', '_name': 'Seduction'},
      {'_id': '066', '_name': 'Scat'},
      {'_id': '067', '_name': 'Sci-Fi'},
      {'_id': '068', '_name': 'Snuff'},
      {'_id': '069', '_name': 'Sixty-Nine Position'},
      {'_id': '070', '_name': 'Spanking'},
      {'_id': '071', '_name': 'Sperm Play'},
      {'_id': '072', '_name': 'Supernatural'},
      {'_id': '073', '_name': 'Super Beings'},
      {'_id': '074', '_name': 'Tentacles'},
      {'_id': '075', '_name': 'Torture'},
      {'_id': '076', '_name': 'Toys'},
      {'_id': '077', '_name': 'Transgender'},
      {'_id': '078', '_name': 'Transformation'},
      {'_id': '079', '_name': 'Unavailable'},
      {'_id': '080', '_name': 'Vanilla Sex'},
      {'_id': '081', '_name': 'Virgin Play'},
      {'_id': '082', '_name': 'Watersports'},
      {'_id': '083', '_name': 'Wax Play'},
      {'_id': '084', '_name': 'Wet & Messy'},
      {'_id': '085', '_name': 'Size Difference'},
      {'_id': '086', '_name': 'Clonecest'},
      {'_id': '087', '_name': 'Plant Sex'},
      {'_id': '088', '_name': 'Prostitution'},
      {'_id': '089', '_name': 'Size Play'},
      {'_id': '090', '_name': 'Body Paints'},
      {'_id': '091', '_name': 'Unusual Skin'},
      {'_id': '092', '_name': 'Pony Play'},
      {'_id': '093', '_name': 'Pregnancy'},
      {'_id': '094', '_name': 'Mind Control'},
      {'_id': '095', '_name': 'Vampirism'},
      {'_id': '096', '_name': 'Voyeurism'},
      {'_id': '097', '_name': 'Silk'},
      {'_id': '098', '_name': 'Doll-Play'},
      {'_id': '099', '_name': 'Angelic Beings'},
      {'_id': '100', '_name': 'Demonic Beings'},
      {'_id': '101', '_name': 'Punishment'},
      {'_id': '102', '_name': 'Teasing'},
      {'_id': '103', '_name': 'Tickling'},
      {'_id': '104', '_name': 'Feather-Play'},
      {'_id': '105', '_name': 'Tail Sex'},
      {'_id': '106', '_name': 'Anthropomorphic'},
      {'_id': '107', '_name': 'Rimming'},
      {'_id': '108', '_name': 'Boobie-sex'},
      {'_id': '109', '_name': 'Tribadism'},
      {'_id': '110', '_name': 'Frottage'},
      {'_id': '111', '_name': 'Glasses'},
      {'_id': '112', '_name': 'Lingerie'},
      {'_id': '113', '_name': 'Clothes'},
      {'_id': '114', '_name': 'Piercings'},
      {'_id': '115', '_name': 'Expansion'},
      {'_id': '116', '_name': 'Water Play'},
      {'_id': '117', '_name': 'Masturbation'},
      {'_id': '118', '_name': 'Dirty Talking'},
      {'_id': '119', '_name': 'Objectification'},
      {'_id': '120', '_name': 'Forniphilia'},
      {'_id': '121', '_name': 'Hadaka(Naked) Apron'},
      {'_id': '122', '_name': 'Muscle Fetish'},
      {'_id': '123', '_name': 'Foreplay'},
      {'_id': '124', '_name': 'Parental'},
      {'_id': '125', '_name': 'Mood Altering'},
      {'_id': '126', '_name': 'Unusual Penetration'},
      {'_id': '127', '_name': 'Sensory Deprivation'},
      {'_id': '128', '_name': 'Exotic Dancing'},
      {'_id': '129', '_name': 'Biting/Nibbling'},
      {'_id': '130', '_name': 'Chastity Devices'},
      {'_id': '131', '_name': 'Video Game'},
      {'_id': '132', '_name': 'Comic Book'},
      {'_id': '133', '_name': 'Multi Penetration'},
      {'_id': '134', '_name': 'Enema'},
      {'_id': '135', '_name': 'School Play'},
      {'_id': '136', '_name': 'Non-Sexual'},
      {'_id': '137', '_name': 'Emotional'},
      {'_id': '138', '_name': 'Cuteness'},
      {'_id': '139', '_name': 'Gags'},
      {'_id': '140', '_name': 'Silliness'},
      {'_id': '141', '_name': 'Harem Play'},
      {'_id': '142', '_name': 'Groping/Molesting'},
      {'_id': '143', '_name': 'Smoking'},
      {'_id': '144', '_name': 'Pegging'},
      {'_id': '145', '_name': 'Diapers'},
      {'_id': '146', '_name': 'Oil Play'},
      {'_id': '147', '_name': 'Disability'},
      {'_id': '148', '_name': 'Plump'},
      {'_id': '149', '_name': 'Skinny'},
      {'_id': '150', '_name': 'Kemonomimi'},
      {'_id': '151', '_name': 'Rough Sex'},
      {'_id': '152', '_name': 'Massage'},
      {'_id': '153', '_name': 'Sneezing'},
      {'_id': '154', '_name': 'Creampie'},
      {'_id': '155', '_name': 'Penis Worship'},
      {'_id': '156', '_name': 'Vagina/Clit Worship'},
      {'_id': '157', '_name': 'Breast Worship'},
      {'_id': '158', '_name': 'Ass Worship'},
      {'_id': '159', '_name': 'Force'},
      {'_id': '160', '_name': 'Contraception'},
      {'_id': '161', '_name': 'Handjobs/Fingering'},
      {'_id': '162', '_name': 'Breast Torture'},
      {'_id': '163', '_name': 'Vagina Torture'},
      {'_id': '164', '_name': 'Cock & Ball Torture'},
      {'_id': '165', '_name': 'Long Term'},
      {'_id': '166', '_name': 'Story Running/GMing'},
      {'_id': '167', '_name': 'Draconic Beings'},
      {'_id': '168', '_name': 'IC Non-Consent'},
      {'_id': '169', '_name': 'Rescue Play'},
      {'_id': '170', '_name': 'Grinding'},
      {'_id': '171', '_name': 'Heroes'},
      {'_id': '172', '_name': 'Villains'},
      {'_id': '173', '_name': 'Master/Slave'},
      {'_id': '174', '_name': 'Sandbox'},
      {'_id': '175', '_name': 'Booze'},
      {'_id': '176', '_name': 'Unusual Cocks'},
      {'_id': '177', '_name': 'Cum Inflation'},
      {'_id': '178', '_name': 'Body Swap'},
      {'_id': '179', '_name': 'Music'},
      {'_id': '180', '_name': 'Vaginal Penetration'},
      {'_id': '181', '_name': 'Mind Games'},
      {'_id': '182', '_name': 'Impregnation'},
      {'_id': '183', '_name': 'Breeding'},
      {'_id': '184', '_name': 'Sexual Dimorphism'},
      {'_id': '185', '_name': 'Male Pregnancy'},
      {'_id': '186', '_name': 'Ageplay (Young Characters)'},
      {'_id': '187', '_name': 'Age Difference'},
      {'_id': '188', '_name': 'Cheating'},
      {'_id': '189', '_name': 'Cuckolding'},
      {'_id': '190', '_name': 'Flexibility'},
      {'_id': '191', '_name': 'Self-Oral'},
      {'_id': '192', '_name': 'Mind Break'},
      {'_id': '193', '_name': 'Ahegao'},
      {'_id': '194', '_name': 'Robots'},
      {'_id': '195', '_name': 'Unbirthing'},
      {'_id': '196', '_name': 'Additional/Multiple parts'},
      {'_id': '197', '_name': 'Amputation'},
      {'_id': '198', '_name': 'Modular'},
      {'_id': '199', '_name': 'Monsters'},
      {'_id': '201', '_name': 'Games'},
      {'_id': '202', '_name': 'Extreme Penetration'}
    ]
  },
  components: {
    KinkOpt
  }
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style>
</style>
